### ISSUE TITLE
Proposing to move this repo to the SBT org

### ISSUE THREAD

**Issue by alistair-RG** [sbt/flyway-sbt#93]
Hi everyone,
We think that this repo would be better served as part of the [sbt](https://github.com/sbt/) organization rather than the Flyway one.

[mkurz](https://github.com/mkurz) has been in touch about making this happen. 

Please add a comment if you have any concerns - otherwise we'll aim to do this soon (April/May 2024).

**Comment by mkurz** [comment]
Thanks!
Given that this repo is more or less unmaintained, because current maintainer @davidmweber moved on to other projects (thanks for everything btw) and is not able to invest more time in flyway-sbt, I reached out to him via email to offer my support in maintaining this repo.
Moving the repo to the sbt org also makes sense because most sbt plugins now live under that organization and by doing that it allows us to publish the plugin under the `com.github.sbt` groupId (instead of `io.github.davidmweber`).

Pinging @eed3si9n (maintainer of sbt), are you ok with moving this repo to the sbt org? If so, I will set up gpg keys etc. for publishing.

**Comment by eed3si9n** [comment]
Sure. sgtm

**Comment by dkichler** [comment]
Great news, indeed - thanks to @mkurz and @alistair-RG for making this happen!

**Comment by eed3si9n** [comment]
If you could transfer this repo to me (eed3si9n), I can transfer it to sbt org and create a team to maintain the repo.

**Comment by john-joe-givery** [comment]
@mkurz @alistair-RG Has there been any progress on the transfer? Would definitely appreciate seeing this PR https://github.com/flyway/flyway-sbt/pull/91 released

**Comment by dkichler** [comment]
We have since migrated to using the Flyway CLI for pipelines 😢

**Comment by mkurz** [comment]
@eed3si9n The repo will be transferred in the next days, maybe end of this week or next week. Just that you are aware when you receive the notifications to accept the transfer and move it over to the sbt org. Thanks!

**Comment by john-joe-givery** [comment]
@mkurz @eed3si9n Did the transfer occur, or did you run into issues?

**Comment by eed3si9n** [comment]
I got an email on October 23rd if I'd be around that week, and I replied positively but never heard back again?

**Comment by mkurz** [comment]
@eed3si9n Hmm.. I was in contact with them, I think they are just busy. I wrote them again just now.

**Comment by alistair-RG** [comment]
On the back of that I did prompt our IT team who have the keys - I'll go and see what is going on.

**Comment by eed3si9n** [comment]
ok. I got the invite be an admin of this repo, so I did the transfer.

**Comment by eed3si9n** [comment]
Here's a new release - https://github.com/sbt/flyway-sbt/releases/tag/v9.22.0

**Comment by eed3si9n** [comment]
Sent @xuwei-k, @dkichler, and @davidmweber an invite to https://github.com/orgs/sbt/teams/flyway-sbt-team/members in addition to @mkurz. Any of you can now merge a PR and push a tag to get a release out.

**Comment by dkichler** [comment]
Thanks for pushing this over the line @eed3si9n!

**Comment by mkurz** [comment]
Help is needed to upgrade to latest Flyway 10.21.0:
- #108
